# Generated by Django 5.2.11 on 2026-03-17 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '音乐标签',
                'verbose_name_plural': '音乐标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='曲名')),
                ('artist', models.CharField(blank=True, max_length=120, verbose_name='歌手 / 创作者')),
                ('album', models.CharField(blank=True, max_length=120, verbose_name='专辑')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='封面图链接')),
                ('short_review', models.CharField(blank=True, max_length=240, verbose_name='一句短评')),
                ('why_it_matters', models.TextField(blank=True, verbose_name='为什么喜欢')),
                ('long_note', models.TextField(blank=True, verbose_name='长说明')),
                ('visibility', models.CharField(choices=[('public', '公开可见'), ('login_required', '登录后可见'), ('private', '仅编辑者可见')], default='public', max_length=20, verbose_name='可见性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tag_links', models.ManyToManyField(blank=True, related_name='tracks', to='music.musictag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MusicAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='music/assets/%Y/%m/%d/', verbose_name='文件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('download_enabled', models.BooleanField(default=True, verbose_name='允许下载')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('login_required', '登录后可见'), ('private', '仅编辑者可见')], default='login_required', max_length=20, verbose_name='可见性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='music.musictrack', verbose_name='所属音乐')),
            ],
            options={
                'verbose_name': '音乐文件',
                'verbose_name_plural': '音乐文件',
                'ordering': ['-created_at'],
            },
        ),
    ]
