# Generated by Django 5.2.11 on 2026-03-15 19:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='作者')),
                ('translator', models.CharField(blank=True, max_length=120, verbose_name='译者')),
                ('publisher', models.CharField(blank=True, max_length=120, verbose_name='出版社')),
                ('publish_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='出版年份')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='封面图链接')),
                ('status', models.CharField(choices=[('planned', '想读'), ('reading', '在读'), ('paused', '暂停'), ('finished', '读完'), ('revisiting', '重读')], default='planned', max_length=20, verbose_name='阅读状态')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='标签')),
                ('short_review', models.CharField(blank=True, max_length=240, verbose_name='一句短评')),
                ('why_it_matters', models.TextField(blank=True, verbose_name='为什么重要')),
                ('long_note', models.TextField(blank=True, verbose_name='长笔记')),
                ('reading_started_at', models.DateField(blank=True, null=True, verbose_name='开始阅读')),
                ('reading_finished_at', models.DateField(blank=True, null=True, verbose_name='完成阅读')),
                ('visibility', models.CharField(choices=[('public', '公开可见'), ('login_required', '登录后可见'), ('private', '仅编辑者可见')], default='public', max_length=20, verbose_name='可见性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('ebook', '电子书'), ('note', '笔记附件'), ('audio', '音频'), ('other', '其他')], default='ebook', max_length=20, verbose_name='资源类型')),
                ('file', models.FileField(upload_to='books/assets/%Y/%m/%d/', verbose_name='文件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('reader_enabled', models.BooleanField(default=True, verbose_name='允许在线阅读')),
                ('download_enabled', models.BooleanField(default=True, verbose_name='允许下载')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('login_required', '登录后可见'), ('private', '仅编辑者可见')], default='login_required', max_length=20, verbose_name='可见性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='books.book', verbose_name='所属书籍')),
            ],
            options={
                'verbose_name': '书籍资源',
                'verbose_name_plural': '书籍资源',
                'ordering': ['-created_at'],
            },
        ),
    ]
