# Generated by Django 5.2.11 on 2026-03-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookasset',
            name='reader_enabled',
        ),
        migrations.AlterField(
            model_name='bookasset',
            name='asset_type',
            field=models.CharField(choices=[('ebook', '书籍文件'), ('note', '笔记附件'), ('audio', '音频'), ('other', '其他')], default='ebook', max_length=20, verbose_name='资源类型'),
        ),
    ]
