# Generated by Django 5.2.11 on 2026-03-16 02:07

import django.core.validators
from django.db import migrations, models
import re


TAG_SPLIT_PATTERN = re.compile(r"[\n,，]+")


def migrate_book_tags_and_ratings(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    BookTag = apps.get_model("books", "BookTag")
    db_alias = schema_editor.connection.alias

    tag_cache = {}
    for book in Book.objects.using(db_alias).all():
        updated_fields = []
        if book.rating is not None and 1 <= book.rating <= 5:
            book.rating = min(book.rating * 20, 100)
            updated_fields.append("rating")

        if updated_fields:
            book.save(update_fields=updated_fields)

        raw_tags = getattr(book, "tags", "") or ""
        parsed_tags = [
            item.strip()
            for item in TAG_SPLIT_PATTERN.split(raw_tags)
            if item.strip()
        ]

        for tag_name in parsed_tags:
            normalized = tag_name.casefold()
            if normalized in tag_cache:
                tag = tag_cache[normalized]
            else:
                tag = BookTag.objects.using(db_alias).filter(name__iexact=tag_name).first()
                if tag is None:
                    tag = BookTag.objects.using(db_alias).create(name=tag_name)
                tag_cache[normalized] = tag
            book.tag_links.add(tag)


def restore_book_tags_and_ratings(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    db_alias = schema_editor.connection.alias

    for book in Book.objects.using(db_alias).all():
        restored_tags = ", ".join(book.tag_links.order_by("name").values_list("name", flat=True))
        updated_fields = ["tags"]
        book.tags = restored_tags

        if book.rating is not None and 20 <= book.rating <= 100 and book.rating % 20 == 0:
            book.rating = book.rating // 20
            updated_fields.append("rating")

        book.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_bookasset_reader_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '书籍标签',
                'verbose_name_plural': '书籍标签',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tag_links',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.booktag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='评分'),
        ),
        migrations.RunPython(migrate_book_tags_and_ratings, restore_book_tags_and_ratings),
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
    ]
