# Generated by Django 5.2.11 on 2026-03-16 02:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def migrate_paused_books_to_planned(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    Book.objects.filter(status='paused').update(status='planned')


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_booktag_remove_book_tags_alter_book_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='word_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='字数（万字）'),
        ),
        migrations.RunPython(
            migrate_paused_books_to_planned,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('planned', '想读'), ('reading', '在读'), ('finished', '读完'), ('revisiting', '重读')], default='planned', max_length=20, verbose_name='阅读状态'),
        ),
    ]
