# Generated by Django 5.2.11 on 2026-03-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(blank=True, max_length=280, verbose_name='摘要')),
                ('markdown_content', models.TextField(blank=True, verbose_name='Markdown 正文')),
                ('source_file', models.FileField(blank=True, upload_to='articles/source/%Y/%m/%d/', verbose_name='Markdown 源文件')),
                ('source_filename', models.CharField(blank=True, max_length=255, verbose_name='源文件名')),
                ('visibility', models.CharField(choices=[('public', '公开可见'), ('login_required', '登录后可见'), ('private', '仅编辑者可见')], default='public', max_length=20, verbose_name='可见性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-updated_at', 'title'],
            },
        ),
    ]
