# Generated by Django 5.2.11 on 2026-03-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SceneryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('short_note', models.CharField(blank=True, max_length=240, verbose_name='一句说明')),
                ('why_it_matters', models.TextField(blank=True, verbose_name='为什么记得这里')),
                ('long_note', models.TextField(blank=True, verbose_name='长说明')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='拍摄时间')),
                ('timezone_name', models.CharField(blank=True, max_length=64, verbose_name='时区')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='省份 / 州')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='区县 / 区域')),
                ('place_name', models.CharField(blank=True, max_length=160, verbose_name='地点名')),
                ('location_text', models.CharField(blank=True, max_length=255, verbose_name='地址说明')),
                ('visibility', models.CharField(choices=[('public', '公开可见'), ('login_required', '登录后可见'), ('private', '仅编辑者可见')], default='public', max_length=20, verbose_name='可见性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '景色记录',
                'verbose_name_plural': '景色记录',
                'ordering': ['-captured_at', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SceneryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scenery/photos/%Y/%m/%d/', verbose_name='图片')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='高度')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='该图拍摄时间')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度')),
                ('exif_payload', models.JSONField(blank=True, default=dict, verbose_name='EXIF 信息')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='scenery.sceneryentry', verbose_name='所属景色')),
            ],
            options={
                'verbose_name': '景色图片',
                'verbose_name_plural': '景色图片',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
